# Form implementation generated from reading ui file 'DICOM_VIEWER/gui/dicom_v0_0_2.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(725, 586)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toolButton = QtWidgets.QToolButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton.sizePolicy().hasHeightForWidth())
        self.toolButton.setSizePolicy(sizePolicy)
        self.toolButton.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(11)
        font.setBold(True)
        self.toolButton.setFont(font)
        self.toolButton.setAutoFillBackground(True)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("DICOM_VIEWER/gui/../assets/icons8-layer-48-2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton.setIcon(icon)
        self.toolButton.setIconSize(QtCore.QSize(64, 48))
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        self.toolButton_2 = QtWidgets.QToolButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_2.sizePolicy().hasHeightForWidth())
        self.toolButton_2.setSizePolicy(sizePolicy)
        self.toolButton_2.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(11)
        font.setBold(True)
        self.toolButton_2.setFont(font)
        self.toolButton_2.setAutoFillBackground(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("DICOM_VIEWER/gui/../assets/icons8-coordinate-system-80-2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_2.setIcon(icon1)
        self.toolButton_2.setIconSize(QtCore.QSize(64, 48))
        self.toolButton_2.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_2.setObjectName("toolButton_2")
        self.horizontalLayout.addWidget(self.toolButton_2)
        self.toolButton_3 = QtWidgets.QToolButton(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolButton_3.sizePolicy().hasHeightForWidth())
        self.toolButton_3.setSizePolicy(sizePolicy)
        self.toolButton_3.setMaximumSize(QtCore.QSize(72, 72))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setPointSize(11)
        font.setBold(True)
        self.toolButton_3.setFont(font)
        self.toolButton_3.setAutoFillBackground(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("DICOM_VIEWER/gui/../assets/icons8-3d-object-50-2.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_3.setIcon(icon2)
        self.toolButton_3.setIconSize(QtCore.QSize(64, 48))
        self.toolButton_3.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextUnderIcon)
        self.toolButton_3.setObjectName("toolButton_3")
        self.horizontalLayout.addWidget(self.toolButton_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 10)
        self.verticalLayout_3.addWidget(self.widget)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.pageMPR = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pageMPR.sizePolicy().hasHeightForWidth())
        self.pageMPR.setSizePolicy(sizePolicy)
        self.pageMPR.setObjectName("pageMPR")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.pageMPR)
        self.verticalLayout.setObjectName("verticalLayout")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(10)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.winCenterSlider = QtWidgets.QSlider(parent=self.pageMPR)
        self.winCenterSlider.setStyleSheet("Qslider::groove:horizontal{\n"
"background: #CC5DE8;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(177, 164, 255);\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -6px 0;\n"
"    border-radius: 12px;\n"
"}\n"
"")
        self.winCenterSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.winCenterSlider.setObjectName("winCenterSlider")
        self.verticalLayout_7.addWidget(self.winCenterSlider)
        self.Wcenter = QtWidgets.QLabel(parent=self.pageMPR)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.Wcenter.setFont(font)
        self.Wcenter.setIndent(4)
        self.Wcenter.setObjectName("Wcenter")
        self.verticalLayout_7.addWidget(self.Wcenter)
        self.horizontalLayout_7.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.winWidthSlider = QtWidgets.QSlider(parent=self.pageMPR)
        self.winWidthSlider.setStyleSheet("Qslider::groove:horizontal{\n"
"background: #CC5DE8;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(177, 164, 255);\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -6px 0;\n"
"    border-radius: 12px;\n"
"}\n"
"")
        self.winWidthSlider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.winWidthSlider.setObjectName("winWidthSlider")
        self.verticalLayout_8.addWidget(self.winWidthSlider)
        self.Wwidth = QtWidgets.QLabel(parent=self.pageMPR)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.Wwidth.setFont(font)
        self.Wwidth.setIndent(4)
        self.Wwidth.setObjectName("Wwidth")
        self.verticalLayout_8.addWidget(self.Wwidth)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.horizontalLayout_7.setStretch(0, 8)
        self.horizontalLayout_7.setStretch(1, 8)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(36)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.axial = QtWidgets.QLabel(parent=self.pageMPR)
        self.axial.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.axial.setFont(font)
        self.axial.setIndent(4)
        self.axial.setObjectName("axial")
        self.horizontalLayout_3.addWidget(self.axial)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.coronal = QtWidgets.QLabel(parent=self.pageMPR)
        self.coronal.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.coronal.setFont(font)
        self.coronal.setIndent(4)
        self.coronal.setObjectName("coronal")
        self.horizontalLayout_3.addWidget(self.coronal)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.sagittal = QtWidgets.QLabel(parent=self.pageMPR)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sagittal.sizePolicy().hasHeightForWidth())
        self.sagittal.setSizePolicy(sizePolicy)
        self.sagittal.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.sagittal.setFont(font)
        self.sagittal.setIndent(4)
        self.sagittal.setObjectName("sagittal")
        self.horizontalLayout_3.addWidget(self.sagittal)
        self.horizontalLayout_3.setStretch(0, 3)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 3)
        self.horizontalLayout_3.setStretch(3, 1)
        self.horizontalLayout_3.setStretch(4, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.axial_slider = QtWidgets.QSlider(parent=self.pageMPR)
        self.axial_slider.setStyleSheet("Qslider::groove:horizontal{\n"
"background: #CC5DE8;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(177, 164, 255);\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -6px 0;\n"
"    border-radius: 12px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #8B5DE8;  /* filled part */\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: #000;  /* filled part */\n"
"    border-radius: 10px;\n"
"}")
        self.axial_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.axial_slider.setObjectName("axial_slider")
        self.horizontalLayout_4.addWidget(self.axial_slider)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.coronal_slider = QtWidgets.QSlider(parent=self.pageMPR)
        self.coronal_slider.setStyleSheet("Qslider::groove:horizontal{\n"
"background: #CC5DE8;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(177, 164, 255);\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -6px 0;\n"
"    border-radius: 12px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #8B5DE8;  /* filled part */\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: #000;  /* filled part */\n"
"    border-radius: 10px;\n"
"}")
        self.coronal_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.coronal_slider.setObjectName("coronal_slider")
        self.horizontalLayout_4.addWidget(self.coronal_slider)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem4)
        self.sagittal_slider = QtWidgets.QSlider(parent=self.pageMPR)
        self.sagittal_slider.setStyleSheet("Qslider::groove:horizontal{\n"
"background: #CC5DE8;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(177, 164, 255);\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -6px 0;\n"
"    border-radius: 12px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #8B5DE8;  /* filled part */\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: #000;  /* filled part */\n"
"    border-radius: 10px;\n"
"}")
        self.sagittal_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.sagittal_slider.setObjectName("sagittal_slider")
        self.horizontalLayout_4.addWidget(self.sagittal_slider)
        self.horizontalLayout_4.setStretch(0, 3)
        self.horizontalLayout_4.setStretch(1, 1)
        self.horizontalLayout_4.setStretch(2, 3)
        self.horizontalLayout_4.setStretch(3, 1)
        self.horizontalLayout_4.setStretch(4, 3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout_4.setStretch(0, 1)
        self.verticalLayout_4.setStretch(1, 10)
        self.verticalLayout_4.setStretch(2, 1)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.stackedWidget.addWidget(self.pageMPR)
        self.page3D = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.page3D.sizePolicy().hasHeightForWidth())
        self.page3D.setSizePolicy(sizePolicy)
        self.page3D.setObjectName("page3D")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.page3D)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.horizontalLayout_5.setContentsMargins(8, 8, 8, 8)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.renderWidget = QtWidgets.QWidget(parent=self.page3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.renderWidget.sizePolicy().hasHeightForWidth())
        self.renderWidget.setSizePolicy(sizePolicy)
        self.renderWidget.setObjectName("renderWidget")
        self.horizontalLayout_5.addWidget(self.renderWidget)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem6)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(9, 13, -1, 3)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.volume_check = QtWidgets.QCheckBox(parent=self.page3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.volume_check.sizePolicy().hasHeightForWidth())
        self.volume_check.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.volume_check.setFont(font)
        self.volume_check.setObjectName("volume_check")
        self.verticalLayout_9.addWidget(self.volume_check)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem7)
        self.bounding_box_check = QtWidgets.QCheckBox(parent=self.page3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bounding_box_check.sizePolicy().hasHeightForWidth())
        self.bounding_box_check.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.bounding_box_check.setFont(font)
        self.bounding_box_check.setObjectName("bounding_box_check")
        self.verticalLayout_9.addWidget(self.bounding_box_check)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem8)
        self.lighting_check = QtWidgets.QCheckBox(parent=self.page3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lighting_check.sizePolicy().hasHeightForWidth())
        self.lighting_check.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.lighting_check.setFont(font)
        self.lighting_check.setObjectName("lighting_check")
        self.verticalLayout_9.addWidget(self.lighting_check)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem9)
        self.label_3 = QtWidgets.QLabel(parent=self.page3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setIndent(4)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_9.addWidget(self.label_3)
        self.opacity_slider = QtWidgets.QSlider(parent=self.page3D)
        self.opacity_slider.setStyleSheet("Qslider::groove:horizontal{\n"
"background: #CC5DE8;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(177, 164, 255);\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -6px 0;\n"
"    border-radius: 12px;\n"
"}")
        self.opacity_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.opacity_slider.setObjectName("opacity_slider")
        self.verticalLayout_9.addWidget(self.opacity_slider)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem10)
        self.label_5 = QtWidgets.QLabel(parent=self.page3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setIndent(4)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_9.addWidget(self.label_5)
        self.brightness_slider = QtWidgets.QSlider(parent=self.page3D)
        self.brightness_slider.setStyleSheet("Qslider::groove:horizontal{\n"
"background: #CC5DE8;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(177, 164, 255);\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -6px 0;\n"
"    border-radius: 12px;\n"
"}")
        self.brightness_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.brightness_slider.setObjectName("brightness_slider")
        self.verticalLayout_9.addWidget(self.brightness_slider)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem11)
        self.label_4 = QtWidgets.QLabel(parent=self.page3D)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Futura")
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setIndent(4)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.threshold_slider = QtWidgets.QSlider(parent=self.page3D)
        self.threshold_slider.setStyleSheet("Qslider::groove:horizontal{\n"
"background: #CC5DE8;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(177, 164, 255);\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -6px 0;\n"
"    border-radius: 12px;\n"
"}\n"
"")
        self.threshold_slider.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.threshold_slider.setObjectName("threshold_slider")
        self.verticalLayout_9.addWidget(self.threshold_slider)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_9.addItem(spacerItem12)
        self.verticalLayout_9.setStretch(0, 1)
        self.verticalLayout_9.setStretch(1, 1)
        self.verticalLayout_9.setStretch(2, 1)
        self.verticalLayout_9.setStretch(3, 1)
        self.verticalLayout_9.setStretch(4, 1)
        self.verticalLayout_9.setStretch(5, 3)
        self.verticalLayout_9.setStretch(6, 1)
        self.verticalLayout_9.setStretch(7, 1)
        self.verticalLayout_9.setStretch(8, 1)
        self.verticalLayout_9.setStretch(9, 1)
        self.verticalLayout_9.setStretch(10, 1)
        self.verticalLayout_9.setStretch(11, 1)
        self.verticalLayout_9.setStretch(12, 1)
        self.verticalLayout_9.setStretch(13, 1)
        self.verticalLayout_9.setStretch(14, 1)
        self.horizontalLayout_5.addLayout(self.verticalLayout_9)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem13)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 4)
        self.horizontalLayout_5.setStretch(2, 1)
        self.horizontalLayout_5.setStretch(3, 2)
        self.horizontalLayout_5.setStretch(4, 1)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_5)
        self.stackedWidget.addWidget(self.page3D)
        self.pageSlice = QtWidgets.QWidget()
        self.pageSlice.setObjectName("pageSlice")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.pageSlice)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(parent=self.pageSlice)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem14)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.horizontalSlider_6 = QtWidgets.QSlider(parent=self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.horizontalSlider_6.sizePolicy().hasHeightForWidth())
        self.horizontalSlider_6.setSizePolicy(sizePolicy)
        self.horizontalSlider_6.setAutoFillBackground(False)
        self.horizontalSlider_6.setStyleSheet("Qslider::groove:horizontal{\n"
"background: #CC5DE8;\n"
"border-radius: 10px\n"
"}\n"
"\n"
"QSlider::handle:horizontal {\n"
"    background: rgb(177, 164, 255);\n"
"    width: 18px;\n"
"    height: 18px;\n"
"    margin: -6px 0;\n"
"    border-radius: 12px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background: #8B5DE8;  /* filled part */\n"
"    border-radius: 10px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: #000;  /* filled part */\n"
"    border-radius: 10px;\n"
"}")
        self.horizontalSlider_6.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.horizontalSlider_6.setTickPosition(QtWidgets.QSlider.TickPosition.NoTicks)
        self.horizontalSlider_6.setObjectName("horizontalSlider_6")
        self.horizontalLayout_2.addWidget(self.horizontalSlider_6)
        self.label = QtWidgets.QLabel(parent=self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.spinBox = QtWidgets.QSpinBox(parent=self.frame)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_2.addWidget(self.spinBox)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout_6.addWidget(self.frame)
        self.horizontalLayout_8.addLayout(self.verticalLayout_6)
        self.stackedWidget.addWidget(self.pageSlice)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_3.setStretch(0, 1)
        self.verticalLayout_3.setStretch(1, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 725, 24))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(parent=MainWindow)
        self.toolBar.setMinimumSize(QtCore.QSize(0, 48))
        self.toolBar.setStyleSheet("border:none;\n"
"background-color:rgb(177, 164, 255);")
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.ToolBarArea.TopToolBarArea, self.toolBar)
        self.actionZoom_in = QtGui.QAction(parent=MainWindow)
        self.actionZoom_in.setCheckable(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("DICOM_VIEWER/gui/../assets/zoom_in_48dp_000000_FILL0_wght500_GRAD200_opsz48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionZoom_in.setIcon(icon3)
        font = QtGui.QFont()
        self.actionZoom_in.setFont(font)
        self.actionZoom_in.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionZoom_in.setIconVisibleInMenu(True)
        self.actionZoom_in.setObjectName("actionZoom_in")
        self.actionZoom_out = QtGui.QAction(parent=MainWindow)
        self.actionZoom_out.setCheckable(True)
        self.actionZoom_out.setChecked(False)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("DICOM_VIEWER/gui/../assets/zoom_out_48dp_000000_FILL0_wght500_GRAD200_opsz48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionZoom_out.setIcon(icon4)
        self.actionZoom_out.setWhatsThis("")
        font = QtGui.QFont()
        font.setPointSize(10)
        self.actionZoom_out.setFont(font)
        self.actionZoom_out.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionZoom_out.setIconVisibleInMenu(True)
        self.actionZoom_out.setObjectName("actionZoom_out")
        self.actionReset = QtGui.QAction(parent=MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("DICOM_VIEWER/gui/../assets/refresh_48dp_000000_FILL0_wght500_GRAD200_opsz48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionReset.setIcon(icon5)
        self.actionReset.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionReset.setObjectName("actionReset")
        self.actionOpen_folder = QtGui.QAction(parent=MainWindow)
        self.actionOpen_folder.setObjectName("actionOpen_folder")
        self.actionRecent = QtGui.QAction(parent=MainWindow)
        self.actionRecent.setObjectName("actionRecent")
        self.actionSave = QtGui.QAction(parent=MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_as = QtGui.QAction(parent=MainWindow)
        self.actionSave_as.setObjectName("actionSave_as")
        self.actionSave_2 = QtGui.QAction(parent=MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("DICOM_VIEWER/gui/../assets/download_48dp_000000_FILL0_wght500_GRAD200_opsz48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionSave_2.setIcon(icon6)
        self.actionSave_2.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionSave_2.setObjectName("actionSave_2")
        self.actionPan = QtGui.QAction(parent=MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("DICOM_VIEWER/gui/../assets/pan_tool_48dp_000000_FILL0_wght500_GRAD200_opsz48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionPan.setIcon(icon7)
        self.actionPan.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionPan.setObjectName("actionPan")
        self.actionundo = QtGui.QAction(parent=MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("DICOM_VIEWER/gui/../assets/undo_48dp_000000_FILL0_wght500_GRAD200_opsz48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionundo.setIcon(icon8)
        self.actionundo.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionundo.setObjectName("actionundo")
        self.actionredo = QtGui.QAction(parent=MainWindow)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("DICOM_VIEWER/gui/../assets/redo_48dp_000000_FILL0_wght500_GRAD200_opsz48.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.actionredo.setIcon(icon9)
        self.actionredo.setMenuRole(QtGui.QAction.MenuRole.NoRole)
        self.actionredo.setObjectName("actionredo")
        self.menuFile.addAction(self.actionOpen_folder)
        self.menuFile.addAction(self.actionRecent)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_as)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionZoom_in)
        self.toolBar.addAction(self.actionZoom_out)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionundo)
        self.toolBar.addAction(self.actionredo)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionPan)
        self.toolBar.addAction(self.actionReset)
        self.toolBar.addAction(self.actionSave_2)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolButton.setText(_translate("MainWindow", "Slice"))
        self.toolButton_2.setText(_translate("MainWindow", "MPR"))
        self.toolButton_3.setText(_translate("MainWindow", "3D"))
        self.Wcenter.setText(_translate("MainWindow", "Window center"))
        self.Wwidth.setText(_translate("MainWindow", "Window width"))
        self.axial.setText(_translate("MainWindow", "Axial"))
        self.coronal.setText(_translate("MainWindow", "Coronal"))
        self.sagittal.setText(_translate("MainWindow", "Sagittal"))
        self.volume_check.setText(_translate("MainWindow", "Volume"))
        self.bounding_box_check.setText(_translate("MainWindow", "Bounding box"))
        self.lighting_check.setText(_translate("MainWindow", "Lighting"))
        self.label_3.setText(_translate("MainWindow", "Opacity"))
        self.label_5.setText(_translate("MainWindow", "Brightness"))
        self.label_4.setText(_translate("MainWindow", "Threshold"))
        self.label.setText(_translate("MainWindow", "25/58"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionZoom_in.setText(_translate("MainWindow", "Zoom in"))
        self.actionZoom_out.setText(_translate("MainWindow", "Zoom out"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionReset.setToolTip(_translate("MainWindow", "Reset"))
        self.actionOpen_folder.setText(_translate("MainWindow", "Open folder"))
        self.actionRecent.setText(_translate("MainWindow", "Recent"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_as.setText(_translate("MainWindow", "Save as"))
        self.actionSave_2.setText(_translate("MainWindow", "Save"))
        self.actionPan.setText(_translate("MainWindow", "Pan"))
        self.actionundo.setText(_translate("MainWindow", "undo"))
        self.actionredo.setText(_translate("MainWindow", "redo"))
